### PR TITLE
[WIP] - preparing for minimesos 0.6.0

### PR DESCRIPTION
**Pull request by sadovnikov**
Compilation errors are resolved. However the following two system tests fail locally:
* DeploymentSystemTest. willForwardDataToElasticsearchInDockerMode
* DeploymentSystemTest. willStartNewExecutorIfOldExecutorFails

### CODE REVIEW

**Comment by sadovnikov** [comment]
for `willStartNewExecutorIfOldExecutorFails` executors keep on exiting...
```
vikmac:mesos-logstash vik$ docker ps -a
CONTAINER ID        IMAGE                                                COMMAND                  CREATED                  STATUS                              PORTS                          NAMES
e213e2ac2f08        mesos/logstash-executor:latest                       "/tmp/start-executor."   Less than a second ago   Up Less than a second                                              mesos-a8564507-2a7c-4866-a4ba-48005d25ae2e-S0.88b456d0-9f61-4159-a0f7-948ed94cba2a
c4bf9ecf4836        mesos/logstash-executor:latest                       "/tmp/start-executor."   10 seconds ago           Exited (0) Less than a second ago                                  mesos-a8564507-2a7c-4866-a4ba-48005d25ae2e-S0.464db4c2-ddb8-47d3-b2f9-0de5cd37cb73
5453fd64e364        mesos/logstash-executor:latest                       "/tmp/start-executor."   21 seconds ago           Exited (0) 11 seconds ago                                          mesos-a8564507-2a7c-4866-a4ba-48005d25ae2e-S0.c11779aa-d6ba-4cb5-91e5-6be731e35302
87ce8b9ab9a2        mesos/logstash-executor:latest                       "/tmp/start-executor."   32 seconds ago           Exited (0) 22 seconds ago                                          mesos-a8564507-2a7c-4866-a4ba-48005d25ae2e-S0.23dc73c2-af31-481c-843f-f8e41b61bbc7
4c14cab7a3fe        mesos/logstash-executor:latest                       "/tmp/start-executor."   43 seconds ago           Exited (0) 33 seconds ago                                          mesos-a8564507-2a7c-4866-a4ba-48005d25ae2e-S0.3bb00de6-4f6f-46d0-b311-74b05a58cfb5
eacd792330c2        mesos/logstash-executor:latest                       "/tmp/start-executor."   53 seconds ago           Exited (0) 43 seconds ago                                          mesos-a8564507-2a7c-4866-a4ba-48005d25ae2e-S0.2baf98f0-5852-4483-acb4-fb1bfc99d561
c8c9058be8f8        mesos/logstash-executor:latest                       "/tmp/start-executor."   About a minute ago       Exited (0) 54 seconds ago                                          mesos-a8564507-2a7c-4866-a4ba-48005d25ae2e-S0.00b6e279-2a2e-4553-a126-f998b9975132

```

**Comment by mwl** [comment]
@sadovnikov I've improved these two test dramatically on the `feature/109-external-configuration` branch. Which isn't finished yet, so you might want to hold your horses a little bit on this PR.

**Comment by sadovnikov** [comment]
@mwl right... I created this branch as an extra way to test new version of `minimesos` before releasing it... I think I need to spend sometime figuring out what's happenning

**Comment by mwl** [comment]
I haven't looked at the issues on this branch. But one of the issues is that the executor changes it's status to `RUNNING` before Logstash is ready to accept incoming messages. Sometimes that can take up to 30 seconds(!).

**Comment by sadovnikov** [comment]
will recreate the branch from `feature/109-external-configuration`

**Pull request closed without merging**
